[project]
name = "mcp-server-with-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.3",
    "fastmcp>=2.14.5",
    "langchain-mcp-adapters>=0.2.1",
    "langchain[huggingface]>=1.2.9",
]
